export const BASE_URL = process.env.NODE_ENV === 'development' ? 'http://localhost:5000' : '';
export const USERS_URL = '/api/users';
export const ARTICLE_URL = '/api/articles';

export const LANGUAGES = {
    en: { code: 'en', name: 'English' },
    es: { code: 'es', name: 'Español' },
    fr: { code: 'fr', name: 'Français' },
    de: { code: 'de', name: 'Deutsch' },
    pt: { code: 'pt', name: 'Português' },
};

export const TRANSLATIONS = {
    en: {
        siteTitle: 'The International Articles',
        dashboard: 'Dashboard',
        articles: 'Articles',
        myArticles: 'My Articles',
        menu: 'Menu',
        signIn: 'Sign In',
        logout: 'Logout',
        searchPlaceholder: 'Search...',
        writeArticle: 'Write Article',
        share: 'Share',
        hi: 'Hi',
        featuredArticle: 'Featured Article',
        recentArticles: 'Recent Articles',
        email: 'Email',
        login: 'Login',
        dontHaveAccount: "Don't have an account?",
        signUp: 'Sign Up',
        account: 'Your Account',
        name: 'Name',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        update: 'Update',
        passwordsMismatch: 'Passwords do not match',
        profileUpdated: 'Profile updated successfully',
        register: 'Register',
        submit: 'Sign Up',
        alreadyHaveAccount: 'Already have an account?',
    },
    es: {
        siteTitle: 'Los Artículos Internacionales',
        dashboard: 'Tablero',
        articles: 'Artículos',
        myArticles: 'Mis Artículos',
        menu: 'Menú',
        signIn: 'Iniciar sesión',
        logout: 'Cerrar sesión',
        searchPlaceholder: 'Buscar...',
        writeArticle: 'Escribir Artículo',
        share: 'Compartir',
        hi: 'Hola',
        featuredArticle: 'Artículo Destacado',
        recentArticles: 'Artículos Recientes',
        email: 'Correo electrónico',
        login: 'Iniciar sesión',
        dontHaveAccount: '¿No tienes una cuenta?',
        signUp: 'Regístrate',
        account: 'Tu Cuenta',
        name: 'Nombre',
        password: 'Contraseña',
        confirmPassword: 'Confirmar Contraseña',
        update: 'Actualizar',
        passwordsMismatch: 'Las contraseñas no coinciden',
        profileUpdated: 'Perfil actualizado con éxito',
        register: 'Registrarse',
        submit: 'Registrarse',
        alreadyHaveAccount: '¿Ya tienes una cuenta?',
    },
    fr: {
        siteTitle: 'Les Articles Internationaux',
        dashboard: 'Tableau de bord',
        articles: 'Articles',
        myArticles: 'Mes Articles',
        menu: 'Menu',
        signIn: 'Se connecter',
        logout: 'Se déconnecter',
        searchPlaceholder: 'Rechercher...',
        writeArticle: 'Écrire un Article',
        share: 'Partager',
        hi: 'Salut',
        featuredArticle: 'Article en Vedette',
        recentArticles: 'Articles Récents',
        email: 'Email',
        login: 'Se connecter',
        dontHaveAccount: "Vous n'avez pas de compte?",
        signUp: "S'inscrire",
        account: 'Votre Compte',
        name: 'Nom',
        password: 'Mot de passe',
        confirmPassword: 'Confirmer le mot de passe',
        update: 'Mettre à jour',
        passwordsMismatch: 'Les mots de passe ne correspondent pas',
        profileUpdated: 'Profil mis à jour avec succès',
        register: "S'inscrire",
        submit: "S'inscrire",
        alreadyHaveAccount: 'Vous avez déjà un compte?',
    },
    de: {
        siteTitle: 'Die Internationalen Artikel',
        dashboard: 'Armaturenbrett',
        articles: 'Artikel',
        myArticles: 'Meine Artikel',
        menu: 'Menü',
        signIn: 'Anmelden',
        logout: 'Abmelden',
        searchPlaceholder: 'Suchen...',
        writeArticle: 'Artikel Schreiben',
        share: 'Teilen',
        hi: 'Hallo',
        featuredArticle: 'Empfohlener Artikel',
        recentArticles: 'Neueste Artikel',
        email: 'E-Mail',
        login: 'Einloggen',
        dontHaveAccount: 'Hast du ein Konto?',
        signUp: 'Registrieren',
        account: 'Ihr Konto',
        name: 'Name',
        password: 'Passwort',
        confirmPassword: 'Passwort bestätigen',
        update: 'Aktualisieren',
        passwordsMismatch: 'Passwörter stimmen nicht überein',
        profileUpdated: 'Profil erfolgreich aktualisiert',
        register: 'Registrieren',
        submit: 'Anmelden',
        alreadyHaveAccount: 'Hast du bereits ein Konto?',
    },
    pt: {
        siteTitle: 'Os Artigos Internacionais',
        dashboard: 'Painel',
        articles: 'Artigos',
        myArticles: 'Meus Artigos',
        menu: 'Menu',
        signIn: 'Entrar',
        logout: 'Sair',
        searchPlaceholder: 'Pesquisar...',
        writeArticle: 'Escrever Artigo',
        share: 'Compartilhar',
        hi: 'Oi',
        featuredArticle: 'Artigo em Destaque',
        recentArticles: 'Artigos Recentes',
        email: 'E-mail',
        login: 'Entrar',
        dontHaveAccount: 'Não tem uma conta?',
        signUp: 'Registrar',
        account: 'Sua Conta',
        name: 'Nome',
        password: 'Senha',
        confirmPassword: 'Confirmar Senha',
        update: 'Atualizar',
        passwordsMismatch: 'As senhas não coincidem',
        profileUpdated: 'Perfil atualizado com sucesso',
        register: 'Registrar',
        submit: 'Registrar',
        alreadyHaveAccount: 'Já tem uma conta?',
    },
};
